### ISSUE TITLE
Even when updating the same item, an animation is called and an exception by the same Key is raised.

### ISSUE THREAD

**Issue by kouroku-room** [canopas/animated_reorderable_list#98]
If we are creating an application of a certain size, we will probably use Freezed to create the data for the items to be displayed in the list.
And, we will often use Riverpod to manipulate the list.

However, when editing an item in a Freezed list, an exception occurs, perhaps because an animation occurs even though the item is the same (i.e., the same Key).

# Environment

<details><summary>flutter doctor -v</summary>

```bash
C:\src\sample_for_issue git:[main]
flutter doctor -v
[√] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.22631.4602], locale ja-JP)
    • Flutter version 3.27.0 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (12 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\sugur\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio Koala Feature Drop
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "17.0.11" 2024-04-16

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "21.0.3" 2024-04-16

[√] VS Code (version 1.96.2)
    • VS Code at C:\Users\sugur\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4602]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.205
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.99

[√] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

# Example Code

I have created a sample app.
https://github.com/kouroku-room/sample_for_issue/tree/ba4d5e464e5678392941e33d253215a41bde46da

<details><summary>Example Code</summary>

```main.dart
import 'package:animated_reorderable_list/animated_reorderable_list.dart';
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'main.freezed.dart';
part 'main.g.dart';

@freezed
class MyListItem with _$MyListItem {
  const factory MyListItem({
    required String id,
    @Default('') String text,
  }) = _MyListItem;
}

@riverpod
class MyListItemViewModel extends _$MyListItemViewModel {
  @override
  List<MyListItem> build() {
    return [
      MyListItem(
        id: '1',
        text: '1',
      ),
      MyListItem(
        id: '2',
        text: '2',
      ),
      MyListItem(
        id: '3',
        text: '3',
      ),
    ];
  }

  void editItem(int index, String text) {
    final newList = [...state];
    newList[index] = newList[index].copyWith(text: text);
    state = newList;
  }

  void onReorder(int oldIndex, int newIndex) {
    final newList = [...state];
    final item = newList.removeAt(oldIndex);
    newList.insert(newIndex, item);
    state = newList;
  }
}

void main() {
  runApp(ProviderScope(child: const MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        actions: [
          Consumer(builder: (context, ref, child) {
            return IconButton(
              icon: const Icon(Icons.add),
              onPressed: () {
                ref
                    .read(myListItemViewModelProvider.notifier)
                    .editItem(1, 'edited');
              },
            );
          }),
        ],
      ),
      body: SafeArea(
        child: Consumer(builder: (context, ref, child) {
          final List<MyListItem> items = ref.watch(myListItemViewModelProvider);

          return AnimatedReorderableListView(
            items: items,
            onReorder: (oldIndex, newIndex) => ref
                .read(myListItemViewModelProvider.notifier)
                .onReorder(oldIndex, newIndex),
            itemBuilder: (context, index) {
              final item = items[index];
              return ListTile(
                key: ValueKey(item.id),
                title: Text(item.text),
              );
            },
          );
        }),
      ),
    );
  }
}
```

</details>

# Procedure

1. Create the above code and execute the following code
`dart run build_runner build --delete-conflicting-outputs`

1. Run the app and tap the AppBar action icon.

The following exceptions occur.

```bash
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [_MotionBuilderItemGlobalKey _MotionBuilderItemGlobalKey#d9200] was used by multiple widgets. The parents of those widgets were:
- FadeTransition(opacity: AnimationController#055fd(◀ 1.000)➩CurveTween(curve: Interval(0.0⋯1.0))➩Tween<double>(0.0 → 1.0)➩1.0, renderObject: RenderAnimatedOpacity#b7aea relayoutBoundary=up7)
- RepaintBoundary(renderObject: RenderRepaintBoundary#b0dbc relayoutBoundary=up4)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:3205:13)
#1      _LinkedHashMapMixin.forEach (dart:_compact_hash:726:13)
#2      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:3149:20)
#3      _LinkedHashMapMixin.forEach (dart:_compact_hash:726:13)
#4      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:36)
#5      BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:3213:6)
#6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:3267:11)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3342:8)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1183:19)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#13     _invoke (dart:ui/hooks.dart:312:13)
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:427:5)
#15     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```

**Comment by kouroku-room** [comment]
I noticed a solution to this issue, or rather the reason for `isSameItem: ` argument in this library.

For the code above, you had to add the following code.
```main.dart
isSameItem: (a, b) => a.id == b.id,
```

By adding this code, I found that no animation occurs on the same item and no exception is called.

If so, I think this isSameItem argument is very important and needs to be in a more alert form.

For example: 
* In this library `final bool Function(E a, E b)? isSameItem;` Add more explanation to the dart doc.
Example: “Animation to the same Widget Key raises an exception. Therefore, if the process returns false in the isSameItem argument (= animation is performed), the Widget Key passed in the itemBuilder argument must also be different.”

* Make the isSameItem argument required.

* In the Readme portion of pub.dev, “What if an exception occurs for `Multiple widgets used the same GlobalKey.`?” Add the following

etc.

**Comment by cp-sneha-s** [comment]
@kouroku-room 
Thank you for pointing out this issue and for your detailed feedback. We will add a dedicated section to the README addressing this specific issue.
If you have any additional suggestions or need further assistance, feel free to reach out!
